visitas/apps/citas/urls.py
from django.conf.urls import patterns, url
from .views import IndexView, MainPanelView, CreateCita, DetailCita, EditCita, DeleteCita, CalendarView,CordinateView,EmpresaView


urlpatterns = patterns('',

  # url(r'^$', 'apps.citas.views.index', name='index'),



   url(r'^calendario/$',CalendarView.as_view(), name = 'calendario'),

   url(r'^coordinacion/$',CordinateView.as_view(), name = 'coordinacion'),

    url(r'^empresas/$', EmpresaView.as_view(), name='empresas'),
  #
  #   url(r'^panel/$', 'apps.citas.views.main_panel', name='panel'),
  #   url(r'^panel/cita/nuevo/$', 'apps.citas.views.crear_cita', name='nuevo'),
  #   url(r'^panel/citas/(?P<cita_id>\d+)/$', 'apps.citas.views.detalle_cita', name='detalle'),
  #   url(r'^panel/citas/editar/(?P<pk>\d+)$', 'apps.citas.views.editar_cita', name='editar'),
  #   url(r'^panel/citas/eliminar/(?P<cita_id>\d+)$', 'apps.citas.views.eliminar_cita', name='eliminar'),

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^panel/$', MainPanelView.as_view(), name='panel'),
    url(r'^panel/cita/nuevo/$', CreateCita.as_view(), name='nuevo'),
    url(r'^panel/citas/(?P<pk>\d+)/$', DetailCita.as_view(), name='detalle'),
    url(r'^panel/citas/editar/(?P<pk>\d+)$', EditCita.as_view(), name='editar'),
    url(r'^panel/citas/eliminar/(?P<pk>\d+)$', DeleteCita.as_view(), name='eliminar'),
)

visitas/apps/usuarios/urls.py
from django.conf.urls import patterns, url, include
from .views import EditUser, DetailUser, EditCompanyDocs

urlpatterns = patterns('',
            url(r'^login/$', 'apps.usuarios.views.userlogin', name="login"),
            url(r'^registro/$', 'apps.usuarios.views.userregister', name="registro"),
            url(r'^salir/$', 'apps.usuarios.views.LogOut', name="logout"),
            url(r'^usuario/password/reset/$','django.contrib.auth.views.password_reset',
                {'post_reset_redirect' : '/usario/password/reset/done/'},name="password_reset"),
                (r'^usuario/password/reset/done/$',
                    'django.contrib.auth.views.password_reset_done'),
                (r'^usuario/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                    'django.contrib.auth.views.password_reset_confirm',
                    {'post_reset_redirect' : '/usuario/password/done/'}),
                (r'^usuario/password/done/$',
                    'django.contrib.auth.views.password_reset_complete'),
            url(r'^usuario/password_change/$',
                'django.contrib.auth.views.password_change',
                {'post_change_redirect' : '/usuario/password_change/done/'},
                name="password_change"),
                (r'^usuario/password_change/done/$',
                'django.contrib.auth.views.password_change_done'),
            url(r'^login/$', include('django.contrib.auth.urls')),
            url(r'^registro/recuperar_contrasena/$', include('django.contrib.auth.urls')),
            url(r'^salir/$', 'apps.usuarios.views.LogOut', name="logout"),

            url(r'^usuario/editar/(?P<pk>\d+)/$', EditUser.as_view(), name = 'editar'),
            url(r'^usuario/informacion/(?P<pk>\d+)/$', DetailUser.as_view(), name = 'detalle'),
         #   url(r'^usuario/editar/(?P<pk>\d+)/$', EditCompanyDocs.as_view(), name = 'editar_company')

)

visitas/visitas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'citas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('apps.citas.urls', namespace="citas_app")),
    url(r'^', include('apps.usuarios.urls', namespace="usuarios_app")),
     #url(r'^calendario/', include('django_bootstrap_calendar.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
    )

visitas/apps/citas/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from datetime import date




@property
def is_past_due(self):
    if date.today() > self.date:
        return True
    return False

class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Cita(TimeStampModel):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(editable=False)
    summary = models.TextField(max_length=255)
    content = models.TextField()
    category = models.ForeignKey(Category,blank=True,null=True)
    place = models.CharField(max_length=50)
    start = models.DateTimeField(blank=True,null=True)
    finish = models.DateTimeField(blank=True,null=True)
    imagen = models.ImageField(upload_to='citas',blank=True,null=True)
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True, null=True)
  # empresa = models.ForeignKey('usuarios.UserCompany')

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Cita, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Assistant(TimeStampModel):
    assistant = models.ForeignKey(settings.AUTH_USER_MODEL)
    cita = models.ManyToManyField(Cita)

    attended = models.BooleanField(default=False)
    has_paid = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s %s" % (self.assistant.username, self.cita.name)


class Comments(TimeStampModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    cita = models.ForeignKey(Cita)

    content = models.TextField()

    def __unicode__(self):
        return "%s %s" % (self.user.username, self.cita.name)

visitas/apps/citas/forms.py
from django import forms
from .models import Cita
#from usuarios.models import User

class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        exclude = ('created','modified',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'company': forms.Select(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
            'start': forms.DateTimeInput(attrs={'class': 'form-control'},),
            'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

visitas/apps/citas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models import Cita, Category
from apps.usuarios.models import User
from .forms import CitaForm


from django.core.urlresolvers import reverse, reverse_lazy

# def index(request):
#     events = Event.objects.all().order_by('-created')[:6]
#     categories = Category.objects.all()
#     return render(request, 'events/index.html', {'events' : events, 'categories':categories})
class IndexView(TemplateView):

    template_name = 'citas/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['citas'] = Cita.objects.all().order_by('-created')[:6]
        context['categories'] = Category.objects.all()
        return context

# def main_panel(request):
#     #organizer = request.user.username
#     events = Event.objects.filter(organizer__username='victorvillazon').order_by('is_free', '-created')
#     cantidad_eventos = events.count()
#     return render(request, 'events/panel/panel.html', {'events' : events, 'cantidad': cantidad_eventos})
class MainPanelView(TemplateView):

    template_name = 'citas/panel/panel.html'

    def get_context_data(self, **kwargs):
        context = super(MainPanelView, self).get_context_data(**kwargs)
        context['citas'] = Cita.objects.filter(organizer = self.request.user).order_by( '-created')
        context['cantidad'] = context['citas'].count()
        return context


# def detalle_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)
#     return render(request, 'events/panel/detalle_evento.html', {'event': event})

class DetailCita(DetailView):

    template_name = 'citas/panel/detalle_cita.html'
    model = Cita


# def crear_evento(request):
#     if request.method == "POST":
#         modelform = EventoForm(request.POST, request.FILES)
#         if modelform.is_valid():
#             organizador = User.objects.get(pk=3)
#             nuevo_evento = modelform.save()
#             nuevo_evento.organizer = organizador
#             nuevo_evento.save()
#             return redirect(reverse('events_app:panel'))
#     else:
#         modelform = EventoForm()

#     return render(request, "events/panel/crear_evento.html", {"form": modelform})

class CreateCita(CreateView):

    form_class = CitaForm
    template_name = 'citas/panel/crear_cita.html'
    success_url = reverse_lazy('citas_app:panel')

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(CreateCita, self).form_valid(form)


# def editar_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)

#     if request.method == "POST":
#         modelform = EventoForm(request.POST, request.FILES, instance=event)
#         if modelform.is_valid():
#             modelform.save()
#             return redirect(reverse('events_app:panel'))
#     else:
#         modelform = EventoForm(instance=event)

#     return render(request, "events/panel/editar_evento.html", {"form": modelform, 'event': event})

class EditCita(UpdateView):

    template_name = 'citas/panel/editar_cita.html'
    success_url = reverse_lazy('citas_app:panel')
    model = Cita
    form_class = CitaForm


    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(EditCita, self).form_valid(form)


class DeleteCita(DeleteView):
    template_name = 'citas/panel/eliminar_cita.html'
    model = Cita
    success_url = reverse_lazy('citas_app:panel')
    #toma la cita a eliminar
    context_object_name = 'cita'


# def eliminar_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)

#     if request.method == "POST":
#         event.delete()
#         return redirect(reverse('events_app:panel'))

#     return render(request, "events/panel/eliminar_evento.html", {'event': event})


class CalendarView(TemplateView):

    template_name = 'citas/calendario/calendario.html'


class CordinateView(TemplateView):

    template_name='citas/coordinacion/coordinacion.html'

class EmpresaView(TemplateView):

    template_name='citas/empresas/empresas.html'

visitas/apps/citas/templates/citas/panel/base_panel.html
{% extends "events/base_citas.html" %}

{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/estilos.css' %}">
{% endblock css %}

{% block js %}
    <script src="{% static 'js/bootstrap.js' %}"></script>
{% endblock js %}

visitas/apps/citas/templates/citas/panel/editar_cita.html
{% extends "citas/base_citas.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "citas/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <a href="{% url 'citas_app:panel' %}" class="btn btn-success">
                    <span class="glyphicon glyphicon-chevron-left"></span> Regresar
                </a>
                <strong>Editando: {{ cita.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">

            <div class="col-md-12">

                <form role="form" action="{% url 'citas_app:editar' cita.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Edición de visitas.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.company.label_tag }}</label>
                        {{ form.company }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Inicio de visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Fin de la visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>



                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar visita</button>
                    </div>
                </form>


                      <h4>DOCUMENTACIÓN A CUMPLIMENTAR</h4>
                     <ul id="myTab" class="nav nav-tabs nav-justified">
                     <li class="active"><a href="#empresa" data-toggle="tab">Empresa</a></li>
                     <li><a href="#Visita" data-toggle="tab">Visita</a></li>
                     <li><a href="#trabajador" data-toggle="tab">Trabajador</a></li>
                     <li><a href="#trobajo" data-toggle="tab">Anexos Trobajo</a></li>
                     <li><a href="#parque" data-toggle="tab">Anexos Parque Tecnológico</a></li>
                     </ul>

        </div><!-- /row -->


                    <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="empresa">
                     <table class="table">
                    <tbody>
                        <tr>
                            <th>Nombre</th>
                            <td>{{ UserCompany.name }}</td>
                        </tr>
                        <tr>
                            <th>Revision</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Inicio / Final</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Lugar</th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                         <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="visita">
                     <form role="form" action="{% url 'citas_app:editar' cita.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Edición de visitas.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.company.label_tag }}</label>
                        {{ form.company }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Inicio de visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Fin de la visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>



                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar visita</button>
                    </div>
                </form>
                    </div>
                    <div class="tab-pane fade" id="trabajador">
                     <table class="table">
                    <tbody>
                        <tr>
                            <th>Nombre</th>
                            <td>{{ cita.name }}</td>
                        </tr>
                        <tr>
                            <th>Documento TA2</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Documento Médico</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Fecha de formación</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Documento EPI</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento Médico</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de Información</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de Capacidad</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de TC2</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de seguridad</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento de seguridad social</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de conformidad no ETT</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                          <tr>
                            <th>Documento peligrosidad </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento de protección </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de ICCo </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento de IC Syva </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento PRL03 </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento PRL04 </th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                    <div class="tab-pane fade" id="trobajo">
                    <table class="table">
                    <tbody>
                        <tr>
                            <th>Anexo FA</th>
                            <td>{{ cita.name }}</td>
                        </tr>
                        <tr>
                            <th>Categoría</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Inicio / Final</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Lugar</th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                    <div class="tab-pane fade" id="parque">
                     <table class="table">
                    <tbody>
                        <tr>
                            <th>Anexo IA<th>
                            <td>{{ cita.name }}</td>
                        </tr>
                        <tr>
                            <th>Categoría</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Inicio / Final</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Lugar</th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                    </div>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

visitas/apps/citas/templates/citas/panel/eliminar_cita.html
{% extends "citas/base_citas.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "citas/panel/navbar.html" %}

    <div class="container">

        <div class="page-header">
            <h4>
                <strong>Eliminando: {{ cita.name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">

                <form role="form" action="{% url 'citas_app:eliminar' cita.id %}" method="POST">{% csrf_token %}
                    <p class="">¿Desea eliminar la visita "{{ cita.name }}"?</p>

                    <input type="submit" value="Sí" class="btn btn-danger"> 
                    <a href="{% url 'citas_app:panel' %}" class="btn btn-default">No</a>
                </form>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

visitas/apps/citas/templates/citas/panel/navmenu.html
      <div class="jumbotron">
  <div class="container text-center">
    <h2>COORDINACIÓN SYVA</h2>
  </div>
</div>

visitas/apps/citas/templates/citas/panel/navmenuindex.html
       <nav role="navigation" class="navbar navbar-default">
        <div class="navbar-header">
            <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <a href="/" class="navbar-brand">Menú</a>
        </div>
        <div id="navbarCollapse" class="collapse navbar-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href="/">Inicio</a></li>
                <li><a href="/panel/">Panel de visitas</a></li>
                {% if user.is_authenticated and user.is_staff or user.is_centralita %}
                <li><a href="/calendario/">Calendario</a></li>
                {% endif %}
                {% if user.is_worker %}
                <li><a href="/coordinacion/">Coordinación</a></li>
                {% endif %}
                <li class="dropdown">
                 <a href="#" data-toggle="dropdown" class="dropdown-toggle">Usuario <b class="caret"></b></a>
                {% if user.is_authenticated %}
                    <ul class="dropdown-menu">
                    <li><a href="{% url 'usuarios_app:detalle' user.id %}">Información de usuario</a></li>
                        <li><a href="{% url 'usuarios_app:editar' user.id %}">Edición de usuario</a></li>
                {% endif %}

                </ul>
            </ul>
        </div>
</nav>

visitas/apps/citas/templates/citas/panel/panel.html
{% extends "citas/base_citas.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "citas/panel/navbar.html" %}

     {% include "citas/panel/navmenu.html" %}




         <div class="container">
          <nav role="navigation" class="navbar navbar-default">
             <div class="navbar-header">
                <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a href="#" class="navbar-brand">Menú</a>
            </div>


            <div id="navbarCollapse" class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li ><a href="/">Inicio</a></li>
                    <li class="active"><a href="/panel/">Panel de visitas</a></li>
                    <li><a href="/calendario/">Calendario</a></li>
                    <li><a href="/coordinacion/">Coordinación</a></li>
                    <li><a href="/empresas/">Empresas</a></li>
                </ul>
            </div>

          </nav>

             <div class="page-header">
            <h4>
                <strong>Tienes <span class="label label-warning">{{ cantidad }}</span> visitas pendientes </strong>
                <a class="btn btn-primary pull-right" href="{% url 'citas_app:nuevo' %}">
                    <span class="glyphicon glyphicon-plus"></span> Crear una nueva visita
                </a>
            </h4>
         </div><!-- page-header -->

        <div class="row">
            
            <div class="col-md-12">
                
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th colspan="2">Nombre de la visita</th>
                            <th>Lugar</th>
                            <th>Usuario</th>
                            <th>Empresa</th>
                            <th>Inicio</th>
                            <th>Fin</th>

                            <th class="text-center">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>

                        {% for cita in citas %}
                        <tr>
                            <td>
                                <img src="{{ cita.imagen.url }}" alt="{{ cita.name }}" width="60" class="img-rounded">
                            </td>
                            <td>{{ cita.name }}</td>
                            <td>{{ cita.place }}</td>
                            <td>{{ cita.organizer }}</td>
                             <td>{{ cita. }}</td>
                            <td>{{ cita.start }}</td>
                            <td>{{ cita.finish }}</td>

                            <td class="text-right">
                                <a href="{% url 'citas_app:detalle' cita.id %}" class="btn btn-success"><span class="glyphicon glyphicon-eye-open"></span></a>
                                <a href="{% url 'citas_app:editar' cita.id %}" class="btn btn-warning"><span class="glyphicon glyphicon-pencil"></span></a>
                                <a href="{% url 'citas_app:eliminar' cita.id %}" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}