visitas/apps/citas/urls.py
from django.conf.urls import patterns, url
from .views import IndexView, MainPanelView, CreateCita, DetailCita, EditCita, DeleteCita, CalendarView,CordinateView,EmpresaView


urlpatterns = patterns('',

  # url(r'^$', 'apps.citas.views.index', name='index'),



   url(r'^calendario/$',CalendarView.as_view(), name = 'calendario'),

   url(r'^coordinacion/$',CordinateView.as_view(), name = 'coordinacion'),

    url(r'^empresas/$', EmpresaView.as_view(), name='empresas'),
  #
  #   url(r'^panel/$', 'apps.citas.views.main_panel', name='panel'),
  #   url(r'^panel/cita/nuevo/$', 'apps.citas.views.crear_cita', name='nuevo'),
  #   url(r'^panel/citas/(?P<cita_id>\d+)/$', 'apps.citas.views.detalle_cita', name='detalle'),
  #   url(r'^panel/citas/editar/(?P<pk>\d+)$', 'apps.citas.views.editar_cita', name='editar'),
  #   url(r'^panel/citas/eliminar/(?P<cita_id>\d+)$', 'apps.citas.views.eliminar_cita', name='eliminar'),

    url(r'^$', IndexView.as_view(), name='index'),
    url(r'^panel/$', MainPanelView.as_view(), name='panel'),
    url(r'^panel/cita/nuevo/$', CreateCita.as_view(), name='nuevo'),
    url(r'^panel/citas/(?P<pk>\d+)/$', DetailCita.as_view(), name='detalle'),
    url(r'^panel/citas/editar/(?P<pk>\d+)$', EditCita.as_view(), name='editar'),
    url(r'^panel/citas/eliminar/(?P<pk>\d+)$', DeleteCita.as_view(), name='eliminar'),
)

visitas/apps/usuarios/urls.py
from django.conf.urls import patterns, url, include
from .views import EditUser, DetailUser, EditCompanyDocs

urlpatterns = patterns('',
            url(r'^login/$', 'apps.usuarios.views.userlogin', name="login"),
            url(r'^registro/$', 'apps.usuarios.views.userregister', name="registro"),
            url(r'^salir/$', 'apps.usuarios.views.LogOut', name="logout"),
            url(r'^usuario/password/reset/$','django.contrib.auth.views.password_reset',
                {'post_reset_redirect' : '/usario/password/reset/done/'},name="password_reset"),
                (r'^usuario/password/reset/done/$',
                    'django.contrib.auth.views.password_reset_done'),
                (r'^usuario/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                    'django.contrib.auth.views.password_reset_confirm',
                    {'post_reset_redirect' : '/usuario/password/done/'}),
                (r'^usuario/password/done/$',
                    'django.contrib.auth.views.password_reset_complete'),
            url(r'^usuario/password_change/$',
                'django.contrib.auth.views.password_change',
                {'post_change_redirect' : '/usuario/password_change/done/'},
                name="password_change"),
                (r'^usuario/password_change/done/$',
                'django.contrib.auth.views.password_change_done'),
            url(r'^login/$', include('django.contrib.auth.urls')),
            url(r'^registro/recuperar_contrasena/$', include('django.contrib.auth.urls')),
            url(r'^salir/$', 'apps.usuarios.views.LogOut', name="logout"),

            url(r'^usuario/editar/(?P<pk>\d+)/$', EditUser.as_view(), name = 'editar'),
            url(r'^usuario/informacion/(?P<pk>\d+)/$', DetailUser.as_view(), name = 'detalle'),
         #   url(r'^usuario/editar/(?P<pk>\d+)/$', EditCompanyDocs.as_view(), name = 'editar_company')

)

visitas/visitas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'citas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('apps.citas.urls', namespace="citas_app")),
    url(r'^', include('apps.usuarios.urls', namespace="usuarios_app")),
     #url(r'^calendario/', include('django_bootstrap_calendar.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
    )

visitas/apps/citas/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.conf import settings
from datetime import date




@property
def is_past_due(self):
    if date.today() > self.date:
        return True
    return False

class TimeStampModel(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(editable=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Cita(TimeStampModel):
    name = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(editable=False)
    summary = models.TextField(max_length=255)
    content = models.TextField()
    category = models.ForeignKey(Category,blank=True,null=True)
    place = models.CharField(max_length=50)
    start = models.DateTimeField(blank=True,null=True)
    finish = models.DateTimeField(blank=True,null=True)
    imagen = models.ImageField(upload_to='citas',blank=True,null=True)
    organizer = models.ForeignKey(settings.AUTH_USER_MODEL,blank=True, null=True)
  # empresa = models.ForeignKey('usuarios.UserCompany')

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Cita, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name


class Assistant(TimeStampModel):
    assistant = models.ForeignKey(settings.AUTH_USER_MODEL)
    cita = models.ManyToManyField(Cita)

    attended = models.BooleanField(default=False)
    has_paid = models.BooleanField(default=False)

    def __unicode__(self):
        return "%s %s" % (self.assistant.username, self.cita.name)


class Comments(TimeStampModel):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    cita = models.ForeignKey(Cita)

    content = models.TextField()

    def __unicode__(self):
        return "%s %s" % (self.user.username, self.cita.name)

visitas/apps/citas/forms.py
from django import forms
from .models import Cita
#from usuarios.models import User

class CitaForm(forms.ModelForm):
    class Meta:
        model = Cita
        exclude = ('created','modified',)
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'summary': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'category': forms.Select(attrs={'class': 'form-control'}),
            'company': forms.Select(attrs={'class': 'form-control'}),
            'place': forms.TextInput(attrs={'class': 'form-control'}),
            'start': forms.DateTimeInput(attrs={'class': 'form-control'},),
            'finish': forms.DateTimeInput(attrs={'class': 'form-control'}),
            'imagen': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

visitas/apps/citas/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, CreateView, DetailView, UpdateView, DeleteView
from .models import Cita, Category
from apps.usuarios.models import User
from .forms import CitaForm


from django.core.urlresolvers import reverse, reverse_lazy

# def index(request):
#     events = Event.objects.all().order_by('-created')[:6]
#     categories = Category.objects.all()
#     return render(request, 'events/index.html', {'events' : events, 'categories':categories})
class IndexView(TemplateView):

    template_name = 'citas/index.html'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context['citas'] = Cita.objects.all().order_by('-created')[:6]
        context['categories'] = Category.objects.all()
        return context

# def main_panel(request):
#     #organizer = request.user.username
#     events = Event.objects.filter(organizer__username='victorvillazon').order_by('is_free', '-created')
#     cantidad_eventos = events.count()
#     return render(request, 'events/panel/panel.html', {'events' : events, 'cantidad': cantidad_eventos})
class MainPanelView(TemplateView):

    template_name = 'citas/panel/panel.html'

    def get_context_data(self, **kwargs):
        context = super(MainPanelView, self).get_context_data(**kwargs)
        context['citas'] = Cita.objects.filter(organizer = self.request.user).order_by( '-created')
        context['cantidad'] = context['citas'].count()
        return context


# def detalle_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)
#     return render(request, 'events/panel/detalle_evento.html', {'event': event})

class DetailCita(DetailView):

    template_name = 'citas/panel/detalle_cita.html'
    model = Cita


# def crear_evento(request):
#     if request.method == "POST":
#         modelform = EventoForm(request.POST, request.FILES)
#         if modelform.is_valid():
#             organizador = User.objects.get(pk=3)
#             nuevo_evento = modelform.save()
#             nuevo_evento.organizer = organizador
#             nuevo_evento.save()
#             return redirect(reverse('events_app:panel'))
#     else:
#         modelform = EventoForm()

#     return render(request, "events/panel/crear_evento.html", {"form": modelform})

class CreateCita(CreateView):

    form_class = CitaForm
    template_name = 'citas/panel/crear_cita.html'
    success_url = reverse_lazy('citas_app:panel')

    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(CreateCita, self).form_valid(form)


# def editar_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)

#     if request.method == "POST":
#         modelform = EventoForm(request.POST, request.FILES, instance=event)
#         if modelform.is_valid():
#             modelform.save()
#             return redirect(reverse('events_app:panel'))
#     else:
#         modelform = EventoForm(instance=event)

#     return render(request, "events/panel/editar_evento.html", {"form": modelform, 'event': event})

class EditCita(UpdateView):

    template_name = 'citas/panel/editar_cita.html'
    success_url = reverse_lazy('citas_app:panel')
    model = Cita
    form_class = CitaForm


    def form_valid(self, form):
        form.instance.organizer = self.request.user
        return super(EditCita, self).form_valid(form)


class DeleteCita(DeleteView):
    template_name = 'citas/panel/eliminar_cita.html'
    model = Cita
    success_url = reverse_lazy('citas_app:panel')
    #toma la cita a eliminar
    context_object_name = 'cita'


# def eliminar_evento(request, evento_id):
#     event = get_object_or_404(Event, pk=evento_id)

#     if request.method == "POST":
#         event.delete()
#         return redirect(reverse('events_app:panel'))

#     return render(request, "events/panel/eliminar_evento.html", {'event': event})


class CalendarView(TemplateView):

    template_name = 'citas/calendario/calendario.html'


class CordinateView(TemplateView):

    template_name='citas/coordinacion/coordinacion.html'

class EmpresaView(TemplateView):

    template_name='citas/empresas/empresas.html'

visitas/apps/citas/templates/citas/base_citas.html
{% extends "base.html" %}

{% load staticfiles %}
{% load bootstrap_calendar %}
{% block css %}
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/estilos.css' %}">
        {% bootstrap_calendar_css %}
{% endblock css %}

{% block js %}
    <script src="{% static 'js/jquery.js' %}"></script>
	<script src="{% static 'js/bootstrap.js' %}"></script>
    <script src="{% static 'js/bootstrap-tab.js' %}"></script>
         {% bootstrap_calendar_js language="es-ES" %}
        {% bootstrap_calendar_init language="es-ES" %}
{% endblock js %}

visitas/apps/citas/templates/citas/index.html
{% extends "citas/base_citas.html" %}

{% block title %}Inicio{% endblock title %}

{% block content %}

<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Coordinación Syva</a>
        </div>
 <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav pull-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'citas_app:panel' %}">Hola {{ user.first_name |capfirst }}</a></li>
                     <li><a href="{% url 'usuarios_app:logout' %}">Logout</a></li>
                {% else %}
                <li><a href="{% url 'usuarios_app:login' %}">Entrar</a></li>
                {% endif %}
            </ul>
        </div><!--/.nav-collapse -->
    </div>
</div>

<div class="jumbotron">
  <div class="container text-center">
    <h1>COORDINACIÓN SYVA</h1>
    <p>Coordinación de actividades para empresas externas</p>
    <p>Laboratorios Syva</p>
  </div>
</div>
<div class="container">

    <div class="page-header">
 {% include "citas/panel/navmenuindex.html" %}
        <h4><strong>Citas disponibles</strong></h4>
    </div>

    <div class="row">

        <div class="col-md-2">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-tag"></span></span>
                <select class="form-control">
                    <option>Categoría</option>
                </select>
            </div>
        </div>
        <div class="col-md-8">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-search"></span></span>
                <input type="text" class="form-control" placeholder="Busca la visita">
            </div>
        </div>

    </div>

</div>

<p></p>

<div class="container eventos">
    {% if user.is_authenticated %}
    <div class="row contenedor-eventos">


         </div>
            <div class="row contenedor-eventos">
                   {% for cita in citas %}
                       {% if user.is_staff or user.is_coordinador or user.is_centralita %}
                        <div class="col-sm-1 col-md-3 ">
                            <div class="thumbnail equal">
                                <img src="{{ cita.imagen.url }}" alt="250x180">
                                <div class="caption">
                                    <h4><a href="{% url 'citas_app:panel' %}">{{ cita.name }}</a></h4>
                                    <small class="date">{{ cita.start }}</small>
                                    <div class="place">
                                        <small class="place">{{ cita.place}}</small> /
                                    </div>
                                    <span class="views">{{ cita.views }}</span>
                                </div>
                        </div>

                        {% elif cita.organizer = user  %}
                         <div class="col-sm-1 col-md-3 ">
                            <div class="thumbnail equal">
                                <img src="{{ cita.imagen.url }}" alt="250x180">
                                <div class="caption">
                                    <h4><a href="{% url 'citas_app:panel' %}">{{ cita.name }}</a></h4>
                                    <small class="date">{{ cita.start }}</small>
                                    <div class="place">
                                        <small class="place">{{ cita.place}}</small> /
                                    </div>
                                    <span class="views">{{ cita.views }}</span>
                                </div>
                        </div>
                        {% endif %}
         </div>
        {% endfor %}
    </div>
{% endif %}
</div>

<div class="container categorias">

    <div class="page-header">
        <h4><strong>Categorías relacionadas</strong></h4>
    </div>

    <div class="row">
        <div class="col-sm-1 col-md-12">
        {% for category in categories %}
            <a class="btn btn-default btn-lg btn-fix">
                <span class="glyphicon glyphicon-tag"></span> {{ category.name }}
            </a>
        {% endfor %}
        </div>

    </div>

</div>

<div class="container organizadores">

    <div class="page-header">
        <h4><strong>Organizadores destacados</strong></h4>
    </div>

    <div class="column">

        <div class="col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/300x180" alt="250x180">
                <div class="caption">
                    Nueva actividad
                </div>
            </div>
        </div>


     <div class="row">

        <div class="col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/300x180" alt="250x180">
                <div class="caption">
                    Calendario de acceso
                </div>
            </div>
        </div>


     <div class="row">

        <div class="col-md-4">
            <div class="thumbnail">
                <img src="http://placehold.it/300x180" alt="250x180">
                <div class="caption">
                    Modificación de información
                </div>
            </div>
        </div>

    </div>
 </div>
</div>

{% endblock content %}