visitas/apps/usuarios/urls.py
from django.conf.urls import patterns, url, include
from .views import EditUser, DetailUser, EditCompanyDocs

urlpatterns = patterns('',
            url(r'^login/$', 'apps.usuarios.views.userlogin', name="login"),
            url(r'^registro/$', 'apps.usuarios.views.userregister', name="registro"),
            url(r'^salir/$', 'apps.usuarios.views.LogOut', name="logout"),
            url(r'^usuario/password/reset/$','django.contrib.auth.views.password_reset',
                {'post_reset_redirect' : '/usario/password/reset/done/'},name="password_reset"),
                (r'^usuario/password/reset/done/$',
                    'django.contrib.auth.views.password_reset_done'),
                (r'^usuario/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
                    'django.contrib.auth.views.password_reset_confirm',
                    {'post_reset_redirect' : '/usuario/password/done/'}),
                (r'^usuario/password/done/$',
                    'django.contrib.auth.views.password_reset_complete'),
            url(r'^usuario/password_change/$',
                'django.contrib.auth.views.password_change',
                {'post_change_redirect' : '/usuario/password_change/done/'},
                name="password_change"),
                (r'^usuario/password_change/done/$',
                'django.contrib.auth.views.password_change_done'),
            url(r'^login/$', include('django.contrib.auth.urls')),
            url(r'^registro/recuperar_contrasena/$', include('django.contrib.auth.urls')),
            url(r'^salir/$', 'apps.usuarios.views.LogOut', name="logout"),

            url(r'^usuario/editar/(?P<pk>\d+)/$', EditUser.as_view(), name = 'editar'),
            url(r'^usuario/informacion/(?P<pk>\d+)/$', DetailUser.as_view(), name = 'detalle'),
         #   url(r'^usuario/editar/(?P<pk>\d+)/$', EditCompanyDocs.as_view(), name = 'editar_company')

)

visitas/visitas/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'citas.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^', include('apps.citas.urls', namespace="citas_app")),
    url(r'^', include('apps.usuarios.urls', namespace="usuarios_app")),
     #url(r'^calendario/', include('django_bootstrap_calendar.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += patterns("",
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT,}
        ),
    )

visitas/apps/usuarios/models.py
from django.db import models

from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin

from django.conf import settings


class UserManager(BaseUserManager, models.Manager):
    def _create_user(self, username, email, password, is_staff,
                     is_superuser,is_company,is_worker,is_usuario,is_centralita,is_coordinador, **extra_fields):
        email = self.normalize_email(email)
        if not email:
            raise ValueError('El email debe ser obligatorio')
        user = self.model(username=username, email=email, is_active=True,
                          is_staff=is_staff, is_superuser=is_superuser,is_company=is_company,
                          is_worker = is_worker,is_usuario = is_usuario,is_centralita = is_centralita,
                          is_coordinador = is_coordinador, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, False,
                                 False,False,False,False,False,False, **extra_fields)

    def create_superuser(self, username, email, password=None, **extra_fields):
        return self._create_user(username, email, password, True,
                                 True,False,False,False,False,False, **extra_fields)

class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=100, unique=True)
    email = models.EmailField()
    first_name = models.CharField(max_length=100,blank=True)
    last_name = models.CharField(max_length=100)
    avatar = models.ImageField(upload_to='users',blank=True )

    objects = UserManager()

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    is_company = models.BooleanField(default=False)
    is_worker = models.BooleanField(default=False)
    is_usuario = models.BooleanField(default=False)
    is_centralita = models.BooleanField(default=False)
    is_coordinador = models.BooleanField(default=False)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    def get_short_name(self):
        return self.username



class UserDepartment(User):
    departament = models.CharField(max_length=100)


    class Admin:
        pass

    def __unicode__(self):
        return "%s" % (self.username)

class UserCentral(User):
    plant = models.CharField(max_length=100)

    def __unicode__(self):
        return "%s" % (self.username)


class UserCompany(User):
    name = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    address = models.CharField(max_length=500)
    phone = models.CharField(max_length=7)
    mobile = models.CharField(max_length=7)
    CIF = models.CharField(max_length=100)
    activity = models.CharField(max_length=500,blank=True)
    #revision = models.DateTimeField(blank=True)
    subcontrate = models.CharField(max_length=100)

    class Admin:
        pass

    def __unicode__(self):
        return "%s" % (self.username)


class UserWorkers(UserCompany):
    TA2_date = models.DateTimeField()
    TA2_doc = models.FileField(upload_to='usuarios',blank=True)
    medical = models.DateTimeField()
    information = models.DateTimeField()
    formation_date = models.DateTimeField()
    EPI_date = models.DateTimeField()
    EPI_doc = models.FileField(upload_to='EPI',blank=True)
    medical_doc = models.FileField(upload_to='medical',blank=True)
    information_doc = models.FileField(upload_to='information',blank=True)
    skill_doc = models.FileField(upload_to='skill',blank=True)

    class Admin:
        pass

    def __unicode__(self):
        return "%s" % (self.username)

#class Docs(models.Model):
#    name = models.CharField(max_lenght=500)
#    validate = models.BooleanField()


#class Doc_User(models.Model):
##    doc = models.ForeignKey('Docs')
#    user = models.ForeignKey('User')
#    type_doc = models.Choices(['FA',])
#    read = models.BooleanField()


class UserDocs(models.Model):
    user = models.ForeignKey(UserWorkers, unique=True)
    TC2 = models.FileField(upload_to='TC2',blank=True)
    safe = models.FileField(upload_to='safe',blank=True)
    ssocial = models.FileField(upload_to='ssocial',blank=True)
    notETT = models.FileField(upload_to='notETT',blank=True)
    risk = models.FileField(upload_to='risk',blank=True)
    protection = models.FileField(upload_to='protection',blank=True)
    ICCo = models.CharField(max_length=100)
    ICSyva = models.CharField(max_length=100)
    PRL03 = models.CharField(max_length=100)
    PRL04 = models.CharField(max_length=100)


    def __unicode__(self):
        return "%s" % (self.username)

visitas/apps/usuarios/forms.py
from django import forms
from .models import User


class UserRegisterForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ('username','email','password')
        widgets = {
            'username' : forms.TextInput(attrs =
                {
                    'class' : 'form-control',
                    'placeholder' : 'Ingresa un nombre de usuario'}),
            'email' : forms.TextInput(attrs =
                {
                    'type' : 'email',
                    'class' : 'form-control',
                    'placeholder' : 'Introduce un email'}),
            'password' : forms.TextInput(attrs =
                {
                    'type' :'password',
                    'class' : 'form-control',
                    'placeholder' : 'Introduce un password'
                })
        }

class LoginForm(forms.Form):

    username = forms.CharField(max_length=30,
                            widget=forms.TextInput(attrs={
                               'class' : 'form-control',
                               'placeholder' : 'Inserta tu nombre de usuario'
                           }))

    password = forms.CharField(max_length=30,
                               widget=forms.TextInput(attrs={
                                   'type' : 'password',
                                   'class' : 'form-control',
                                   'placeholder' : 'Inserta tu password'
                               }))

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {}
        widgets = {
            'email' : forms.TextInput(attrs =
                {
                    'type' : 'email',
                    'class' : 'form-control',
                    'placeholder' : 'Introduce un email'}),
            'password' : forms.TextInput(attrs =
                {
                    'type' :'password',
                    'class' : 'form-control',
                    'placeholder' : 'Introduce un password'}),
            'first_name' : forms.TextInput(attrs =
                {
                    'type': 'first_name',
                    'class': 'form-control',
                    'placeholder': 'Introduce tu nombre'}),
            'last_name' : forms.TextInput(attrs=
                {
                    'type': 'last_name',
                    'class': 'form-control',
                    'placeholder': 'Introduce tu apellido'}),
            'avatar' : forms.ClearableFileInput(attrs=
                {
                    'type': 'last_name',
                    'class': 'form-control',
                    'placeholder': 'Introduce un avatar'})
        }

class UserModfForm(forms.ModelForm):
    class Meta:
        model = User
        exclude = ('created','modified',)
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'first_name': forms.Textarea(attrs={'class': 'form-control', 'rows': '2'}),
            'last_name': forms.Select(attrs={'class': 'form-control'}),
            'avatar': forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class CompanyDocsForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {}
        widgets = {
            'TC2': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'safe': forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'ssocial':forms.ClearableFileInput(attrs={'class': 'form-control'}),
           # 'notETT':forms.Checkbox, choices =
            'risk':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'protection':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'ICCo':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'ICSyva':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'PRL03':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'PRL04':forms.ClearableFileInput(attrs={'class': 'form-control'}),
        }

class UserDocsWorkerForm(forms.ModelForm):
    class Meta:
        model = User
        fields = {}
        widgets = {
            #'TA2_date':
            'TA2_doc':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'medical':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'EPI_doc':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'medical_doc':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'information_doc':forms.ClearableFileInput(attrs={'class': 'form-control'}),
            'skill_doc':forms.ClearableFileInput(attrs={'class': 'form-control'}),

        }

visitas/apps/usuarios/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout
from .forms import UserRegisterForm, LoginForm,UserModfForm,CompanyDocsForm
from django.views.generic import UpdateView,DetailView
from .models import User
from .functions import LogIn
from .forms import UserForm
from django.core.urlresolvers import reverse, reverse_lazy

def userlogin(request):
	if request.method == "POST":
		if 'register_form' in request.POST:
			user_register = UserRegisterForm(request.POST)
			if user_register.is_valid():
				User.objects.create_user(username = user_register.cleaned_data['username'],
				 email = user_register.cleaned_data['email'],
				 password = user_register.cleaned_data['password'],
                 first_name = user_register.cleaned_data['first_name'],
                 last_name = user_register.cleaned_data['last_name']
                )
				LogIn(request, user_register.cleaned_data['username'],
						user_register.cleaned_data['password'])
				return redirect('/')
		if 'login_form' in request.POST:
			login_form = LoginForm(request.POST)
			if login_form.is_valid():
				LogIn(request, login_form.cleaned_data['username'],
						login_form.cleaned_data['password'])
				return redirect('/')
	else:
		user_register = UserRegisterForm()
		login_form = LoginForm()
	return render(request, 'usuarios/login.html',
				{'user_register' : user_register, 'login_form' : login_form})

def userregister(request):
	if request.method == "POST":
		if 'register_form' in request.POST:
			user_register = UserRegisterForm(request.POST)
			if user_register.is_valid():
				User.objects.create_user(username = user_register.cleaned_data['username'],
				 email = user_register.cleaned_data['email'],
				 password = user_register.cleaned_data['password'],
                 # first_name = user_register.cleaned_data['first_name'],
                 # last_name = user_register.cleaned_data['last_name']
                )
				LogIn(request, user_register.cleaned_data['username'],
						user_register.cleaned_data['password'])
				return redirect('/')
		if 'login_form' in request.POST:
			login_form = LoginForm(request.POST)
			if login_form.is_valid():
				LogIn(request, login_form.cleaned_data['username'],
						login_form.cleaned_data['password'])
				return redirect('/')
	else:
		user_register = UserRegisterForm()
		login_form = LoginForm()
	return render(request, 'usuarios/registro.html',
				{'user_register' : user_register, 'login_form' : login_form})




def LogOut(request):
    logout(request)
    return redirect('/')


class EditUser(UpdateView):
    template_name = 'usuarios/editar_usuario.html'
    success_url = reverse_lazy('/')
    model = User
    form_class = UserModfForm


class DetailUser(DetailView):
    template_name = 'usuarios/detalle_usuario.html'
    model = User

class EditCompanyDocs(UpdateView):
    template_name = 'usuarios/editar_usuario.html'
    success_url = reverse_lazy('/')
    model = User
    form_class = CompanyDocsForm

visitas/apps/usuarios/templates/usuarios/coordinacion2.html
{% extends "citas/base_citas.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "citas/panel/navbar.html" %}

    <div class="container">

        <div class="row">

            <div class="col-md-12">

                      <h4>DOCUMENTACIÓN A CUMPLIMENTAR</h4>
                     <ul id="myTab" class="nav nav-tabs nav-justified">
                     <li class="active"><a href="#empresa" data-toggle="tab">Empresa</a></li>
                     <li><a href="#Visita" data-toggle="tab">Visita</a></li>
                     <li><a href="#trabajador" data-toggle="tab">Trabajador</a></li>
                     <li><a href="#trobajo" data-toggle="tab">Anexos Trobajo</a></li>
                     <li><a href="#parque" data-toggle="tab">Anexos Parque Tecnológico</a></li>
                     </ul>

        </div><!-- /row -->
              <form role="form" action="{% url 'usuarios_app:editar_company' user.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Edición de documentos de empresa.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.TC2.label_tag }}</label>
                        {{ form.TC2 }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.safe.label_tag }}</label>
                        {{ form.safe }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.company.label_tag }}</label>
                        {{ form.company }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Inicio de visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Fin de la visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>



                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar visita</button>
                    </div>
                </form>


                    <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="empresa">
                     <table class="table">
                    <tbody>
                        <tr>
                            <th>Nombre</th>
                            <td>{{ UserCompany.name }}</td>
                        </tr>
                        <tr>
                            <th>Revision</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Inicio / Final</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Lugar</th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                         <div id="myTabContent" class="tab-content">
                    <div class="tab-pane fade in active" id="visita">
                     <form role="form" action="{% url 'citas_app:editar' cita.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Edición de visitas.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.summary }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.content }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.place.label_tag }}</label>
                        {{ form.place }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.company.label_tag }}</label>
                        {{ form.company }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.start.label_tag }}</label>
                        {{ form.start }}
                        <p class="help-block">Inicio de visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.finish.label_tag }}</label>
                        {{ form.finish }}
                        <p class="help-block">Fin de la visita. DD/MM/AA HH:MM:SS.</p>
                    </div>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.imagen }}
                    </div>



                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar visita</button>
                    </div>
                </form>
                    </div>
                    <div class="tab-pane fade" id="trabajador">
                     <table class="table">
                    <tbody>
                        <tr>
                            <th>Nombre</th>
                            <td>{{ cita.name }}</td>
                        </tr>
                        <tr>
                            <th>Documento TA2</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Documento Médico</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Fecha de formación</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Documento EPI</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento Médico</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de Información</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de Capacidad</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de TC2</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de seguridad</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento de seguridad social</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de conformidad no ETT</th>
                            <td>{{ cita.place }}</td>
                        </tr>
                          <tr>
                            <th>Documento peligrosidad </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento de protección </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento de ICCo </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento de IC Syva </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                        <tr>
                            <th>Documento PRL03 </th>
                            <td>{{ cita.place }}</td>
                        </tr>
                         <tr>
                            <th>Documento PRL04 </th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                    <div class="tab-pane fade" id="trobajo">
                    <table class="table">
                    <tbody>
                        <tr>
                            <th>Anexo FA</th>
                            <td>{{ cita.name }}</td>
                        </tr>
                        <tr>
                            <th>Categoría</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Inicio / Final</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Lugar</th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                    <div class="tab-pane fade" id="parque">
                     <table class="table">
                    <tbody>
                        <tr>
                            <th>Anexo IA<th>
                            <td>{{ cita.name }}</td>
                        </tr>
                        <tr>
                            <th>Categoría</th>
                            <td>{{ cita.category }}</td>
                        </tr>
                        <tr>
                            <th>Contenido</th>
                            <td>{{ cita.content }}</td>
                        </tr>
                        <tr>
                            <th>Inicio / Final</th>
                            <td>{{ cita.start }} / {{ cita.finish }}</td>
                        </tr>
                        <tr>
                            <th>Lugar</th>
                            <td>{{ cita.place }}</td>
                        </tr>

                    </tbody>
                </table>
                    </div>
                    </div>

            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

visitas/apps/usuarios/templates/usuarios/editar_usuario.html
        {% extends "citas/base_citas.html" %}

{% block title %}Panel{% endblock title %}

{% block content %}

    {% include "citas/panel/navbar.html" %}

     {% include "citas/panel/navmenu.html" %}



    <div class="container">
      {% include "citas/panel/navmenuindex.html" %}
        <div class="page-header">
            <h4>

                <strong>Editando: {{ user.first_name }}</strong>
            </h4>
        </div><!-- page-header -->

        <div class="row">
            <div class="col-md-12">
                <form role="form" action="{% url 'usuarios_app:editar' user.id %}" method="POST" enctype="multipart/form-data">{% csrf_token %}
                    <p class="lead"><span class="glyphicon glyphicon-info-sign"></span> Edición de usuario.</p>

                    {% if form.errors %}
                        <div class="alert alert-danger" role="alert">
                            {{ form.errors }}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <label>{{ form.name.label_tag }}</label>
                        {{ form.first_name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.summary.label_tag }}</label>
                        {{ form.last_name }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.content.label_tag }}</label>
                        {{ form.email }}
                    </div>

                    <div class="form-group">
                        <label>{{ form.category.label_tag }}</label>
                        {{ form.category }}
                    </div>

                      <a href="/usuario/password_change" class="btn btn-success">
                    <span>Cambiar contraseña</span>
                    </a>

                    <div class="form-group">
                        <label>{{ form.imagen.label_tag }}</label>
                        {{ form.avatar }}

                    </div>


                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Guardar usuario</button>
                    </div>

                     <tr>
                            {% if user.is_worker = true %}
                            <th>Nombre del trabajador</th>
                            <td>{{ user.first_name }}</td>
                            <th>Fecha de TA2</th>
                            <td>{{ user.TA2_date }}</td>
                            <th>Fecha médica</th>
                            <td>{{ user.medical }}</td>
                            <th>Fecha de información</th>
                            <td>{{ user.information }}</td>
                            <th>Fecha de formación</th>
                            <td>{{ user.formation_date }}</td>
                            <th>Fecha de EPI</th>
                            <td>{{ user.EPI_date }}</td>
                            {% endif %}
                        </tr>

                </form>


            </div><!-- col-md-12 -->

        </div><!-- /row -->

    </div><!-- /container -->

{% endblock content %}

visitas/apps/usuarios/templates/usuarios/password_reset_form.html
{% extends "citas/base_citas.html" %}

{% block title %}Nueva Contraseña {% endblock title %}

{% block content %}
<p>Por favor introduce tu correo para recibir las instrucciones de recuperación</p>

<form action="" method="post">
    <div style="display:none">
        <input type="hidden" value="{{ csrf_token }}" name="csrfmiddlewaretoken">
    </div>
     {{ form.email.errors }}
    <p><label for="id_email">E-mail address:</label> {{ form.email }} <input type="submit" value="Reset password" /></p>
</form>
{% endblock %}